### PR TITLE
-added my part to High Bay site

### PR DESCRIPTION
**Pull request by ryantruitt**

### CODE REVIEW

**Comment by MatthewYork** [comment]
Looks like a broken image. Also, can you add a separator (center aligned) that says "students" That way it forms it's own section.

**Comment by ryantruitt** [comment]
-added Ryan and Grayson and images. Also student divider.

**Comment by MatthewYork** [comment]
image links broken! haha

**Comment by ryantruitt** [comment]
Fixed the images and header

**Pull request merged**
